# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  L1_to_L2:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  L2_to_L3:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  L3_to_L4:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  L4_to_L5:
    has_velocity_limits: true
    max_velocity: 6.98131700798
    has_acceleration_limits: false
    max_acceleration: 0
  L5_to_L6:
    has_velocity_limits: true
    max_velocity: 6.98131700798
    has_acceleration_limits: false
    max_acceleration: 0
  L6_to_L7:
    has_velocity_limits: true
    max_velocity: 6.98131700798
    has_acceleration_limits: false
    max_acceleration: 0
  R1_to_R2:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  R2_to_R3:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  R3_to_R4:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  R4_to_R5:
    has_velocity_limits: true
    max_velocity: 6.98131700798
    has_acceleration_limits: false
    max_acceleration: 0
  body_to_L1:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  body_to_R1:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  leftGripperBase_to_leftGripperR:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  rightGripperBase_to_rightGripperR:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_joint_5_r:
    has_velocity_limits: true
    max_velocity: 6.98131700798
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_joint_6_r:
    has_velocity_limits: true
    max_velocity: 6.98131700798
    has_acceleration_limits: false
    max_acceleration: 0