right_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - R1_to_R2
    - R2_to_R3
    - R3_to_R4
    - R4_to_R5
    - yumi_joint_5_r
    - yumi_joint_6_r
  gains:
    R1_to_R2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    R2_to_R3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    R3_to_R4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    R4_to_R5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yumi_joint_5_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yumi_joint_6_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
right_gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - rightGripperBase_to_rightGripperR
  gains:
    rightGripperBase_to_rightGripperR:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
left_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - L1_to_L2
    - L2_to_L3
    - L3_to_L4
    - L4_to_L5
    - L5_to_L6
    - L6_to_L7
  gains:
    L1_to_L2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L2_to_L3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L3_to_L4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L4_to_L5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L5_to_L6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L6_to_L7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
left_gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - leftGripperBase_to_leftGripperR
  gains:
    leftGripperBase_to_leftGripperR:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
both_arms_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - body_to_L1
    - L1_to_L2
    - L2_to_L3
    - L3_to_L4
    - L4_to_L5
    - L5_to_L6
    - L6_to_L7
    - body_to_R1
    - R1_to_R2
    - R2_to_R3
    - R3_to_R4
    - R4_to_R5
    - yumi_joint_5_r
    - yumi_joint_6_r
  gains:
    body_to_L1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L1_to_L2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L2_to_L3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L3_to_L4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L4_to_L5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L5_to_L6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    L6_to_L7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    body_to_R1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    R1_to_R2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    R2_to_R3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    R3_to_R4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    R4_to_R5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yumi_joint_5_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    yumi_joint_6_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1